import { prisma } from '../lib/prisma';

/**
 * Automatically creates a follow-up booking
 */
export const bookFollowup = async (ownerId: string, data: any) => {
    try {
        const clientName = data.name || data.Name || data.visitorName || 'Follow-up Client';
        const phone = data.phone || data.Phone || data.visitorPhone || '';
        
        // Default follow-up date (3 days from now)
        const date = new Date();
        date.setDate(date.getDate() + 3);

        const booking = await prisma.booking.create({
            data: {
                ownerId,
                clientName,
                phone,
                service: 'Follow-up',
                date,
                status: 'PENDING',
                source: 'Automation',
                notes: `Automatically scheduled follow-up from ${data.trigger || 'system event'}`
            }
        });

        console.log(`[Bookings] Created follow-up booking for ${clientName}`);
        return booking;
    } catch (error) {
        console.error('[Bookings] Create follow-up error:', error);
        throw error;
    }
};

/**
 * Creates a generic booking mapped from automation variables
 */
export const createAutomationBooking = async (ownerId: string, data: any, mapping: any = {}) => {
    try {
        const clientNameField = mapping['guest_name'] || Object.keys(data).find(k => k.toLowerCase().includes('name'));
        const phoneField = mapping['phone'] || Object.keys(data).find(k => k.toLowerCase().includes('phone'));
        const dateField = mapping['booking_date'] || Object.keys(data).find(k => k.toLowerCase().includes('date'));

        const clientName = (clientNameField && data[clientNameField]) || data.Name || data.name || 'Automated Guest';
        const phone = (phoneField && data[phoneField]) || data.Phone || data.phone || '';
        
        let date = new Date();
        date.setDate(date.getDate() + 1); // Default to tomorrow if not found
        
        if (dateField && data[dateField]) {
            const parsed = new Date(data[dateField]);
            if (!isNaN(parsed.getTime())) date = parsed;
        }

        const booking = await prisma.booking.create({
            data: {
                ownerId,
                clientName,
                phone,
                service: 'Automated Booking',
                date,
                status: 'CONFIRMED',
                source: 'Neural Flow',
                notes: 'Automatically generated by Neural Flow automation.'
            }
        });

        console.log(`[Bookings] Created automated booking for ${clientName}`);
        return booking;
    } catch (error) {
        console.error('[Bookings] Create automation booking error:', error);
        throw error;
    }
};
